apiVersion: v1
kind: Service
metadata:
  name: kong-service
spec:
  selector:
    app: kong
  ports:
    - name: kong
      port: 8000
      targetPort: 8000
    - name: kong-api
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      name: kong
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:1.5
        imagePullPolicy: Always
        env:
        - name: KONG_PG_HOST
          value: "kong-db-service"
        - name: KONG_PG_PASSWORD
          value: "kong"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000"
        - name: KONG_PROXY_LISTEN_SSL
          value: "0.0.0.0:8443"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        ports:
          - containerPort: 8000
          - containerPort: 8001
