apiVersion: v1
kind: Service
metadata:
  name: konga-service
spec:
  selector:
    app: konga
  ports:
    - name: konga
      port: 1337
      targetPort: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      name: konga
      labels:
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga:latest
        imagePullPolicy: Always
        env:
        - name: DB_ADAPTER
          value: "postgres"
        - name: DB_HOST
          value: "kong-db-service"
        - name: DB_USER
          value: "kong"
        - name: DB_PASSWORD
          value: "kong"
        - name: TOKEN_SECRET
          value: "ahfdjgjgf79JKLFHJKh978953kgdfjkl"
        - name: DB_DATABASE
          value: "kong"
        - name: NODE_ENV
          value: "production"
        ports:
          - containerPort: 1337